[pytest]
# --cache-clear: Her koşumda eski hafızayı temizler (Senin hayalet data sorununun çözümü)
# -s: Print çıktılarını konsolda gösterir
# -v: Hangi testin hangi veriyle koştuğunu detaylı yazar
# --headed: Tarayıcıyı görünür modda açar
addopts = -s -v --headed --cache-clear

# Testlerin aranacağı klasör
testpaths = tests

# Test dosyalarının isimlendirme kuralı
python_files = test_*.py
